Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "private_network", ip: "192.168.33.11"
    config.vm.provision "shell", inline: <<-SHELL
      curl -sSLf https://get.docker.com | sh
      sudo usermod -aG docker vagrant
    SHELL
  end